// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymouskawbdwajvqytqqr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltb3Vza2F3YmR3YWp2cXl0cXFyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTExNTEsImV4cCI6MjA2NTU4NzE1MX0.5_sojnYd5ODLoROKoMzcRJPXk6y27UlCgVwVb8yQpaI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);